# Generated by Django 4.0 on 2022-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_product_image_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
