# Generated by Django 4.0 on 2022-03-21 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=90, verbose_name='Title(*)')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('status', models.CharField(blank=True, choices=[('p', 'published'), ('d', 'draft')], default='s', max_length=1, null=True, verbose_name='Status(*)')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='auth.user', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-create_date'],
            },
        ),
    ]
